apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: my-app/users-service:latest
          imagePullPolicy: IfNotPresent # Use the image if it exists locally before trying to pull from Docker Hub
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/my-app"
