apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-service
  template:
    metadata:
      labels:
        app: restaurants-service
    spec:
      containers:
        - name: restaurants-service
          image: my-app/restaurants-service:latest
          imagePullPolicy: IfNotPresent # Use the image if it exists locally before trying to pull from Docker Hub
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads   # <- Mount inside your container here
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc